// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260320035424_passwordchange")]
    partial class passwordchange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Xem sản phẩm",
                            Group = "Products",
                            Name = "products.view"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tạo sản phẩm",
                            Group = "Products",
                            Name = "products.create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sửa sản phẩm",
                            Group = "Products",
                            Name = "products.update"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xóa sản phẩm",
                            Group = "Products",
                            Name = "products.delete"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Xem danh mục",
                            Group = "Categories",
                            Name = "categories.view"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Tạo danh mục",
                            Group = "Categories",
                            Name = "categories.create"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Sửa danh mục",
                            Group = "Categories",
                            Name = "categories.update"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Xóa danh mục",
                            Group = "Categories",
                            Name = "categories.delete"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Xem đơn hàng",
                            Group = "Orders",
                            Name = "orders.view"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Tạo đơn hàng",
                            Group = "Orders",
                            Name = "orders.create"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cập nhật trạng thái đơn",
                            Group = "Orders",
                            Name = "orders.update_status"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Hủy đơn hàng",
                            Group = "Orders",
                            Name = "orders.cancel"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Xóa đơn hàng",
                            Group = "Orders",
                            Name = "orders.delete"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Xem tài khoản",
                            Group = "Users",
                            Name = "users.view"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Tạo tài khoản",
                            Group = "Users",
                            Name = "users.create"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Sửa tài khoản",
                            Group = "Users",
                            Name = "users.update"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Xóa tài khoản",
                            Group = "Users",
                            Name = "users.delete"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Khóa tài khoản",
                            Group = "Users",
                            Name = "users.ban"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Xem báo cáo",
                            Group = "Reports",
                            Name = "reports.view"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Xuất báo cáo",
                            Group = "Reports",
                            Name = "reports.export"
                        });
                });

            modelBuilder.Entity("Api.Models.Auth.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("Api.Models.Product.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Api.Models.Product.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Api.Models.Product.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("Api.Models.Product.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsMain")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Api.Models.Product.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("Api.Models.Product.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("Api.Models.Product.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.HasIndex("TypeId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Api.Models.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Api.Models.Auth.UserPermission", b =>
                {
                    b.HasOne("Api.Models.Auth.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.User.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.Models.Product.Product", b =>
                {
                    b.HasOne("Api.Models.Product.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Api.Models.Product.ProductColor", b =>
                {
                    b.HasOne("Api.Models.Product.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Models.Product.ProductImage", b =>
                {
                    b.HasOne("Api.Models.Product.ProductColor", "Color")
                        .WithMany("Images")
                        .HasForeignKey("ColorId");

                    b.HasOne("Api.Models.Product.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Product.ProductSize", "Size")
                        .WithMany("Images")
                        .HasForeignKey("SizeId");

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Api.Models.Product.ProductSize", b =>
                {
                    b.HasOne("Api.Models.Product.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Models.Product.ProductType", b =>
                {
                    b.HasOne("Api.Models.Product.Product", "Product")
                        .WithMany("Types")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Models.Product.ProductVariant", b =>
                {
                    b.HasOne("Api.Models.Product.ProductColor", "Color")
                        .WithMany("Variants")
                        .HasForeignKey("ColorId");

                    b.HasOne("Api.Models.Product.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Product.ProductSize", "Size")
                        .WithMany("Variants")
                        .HasForeignKey("SizeId");

                    b.HasOne("Api.Models.Product.ProductType", "Type")
                        .WithMany("Variants")
                        .HasForeignKey("TypeId");

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Api.Models.Auth.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("Api.Models.Product.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Api.Models.Product.Product", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("Sizes");

                    b.Navigation("Types");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Api.Models.Product.ProductColor", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Api.Models.Product.ProductSize", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Api.Models.Product.ProductType", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Api.Models.User.User", b =>
                {
                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
